name: Build C++ Project - Windows

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      solutionFileName:
        required: true
        type: string
      upload_url:
        required: true
        type: string

jobs:
  build-and-archive:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate Debug Text File
      run: |
        echo "This is a debug file for testing purposes" > debug.txt
      
    - name: Zip the text file
      run: Compress-Archive -Path debug.txt -DestinationPath win-x64-binaries.zip

    - name: Attach binaries to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        upload_url: ${{ inputs.upload_url }}
        asset_path: ./win-x64-binaries.zip
        asset_name: win-x64-binaries.zip
        asset_content_type: application/zip
