name: Publish Docker Image

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      solutionFileName:
        required: true
        type: string

jobs:
  build-and-archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' 

    - name: Build .NET Core Project
      run: dotnet build PreRequisitesSetup/PreRequisitesSetup.csproj --configuration Release

    - name: Run .NET Core Project - Download latest Viewer assets
      env:
         PRIVATE_ACCESS_TOKEN: ${{ secrets.INHERITED_ACCESS_TOKEN }}
      run: dotnet run --project PreRequisitesSetup/PreRequisitesSetup.csproj

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: modelservicecontainersregistry.azurecr.io
        username: modelservicecontainersregistry
        password: ${{ secrets.INHERITED_ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        echo "Building Docker image with tag ${{ inputs.releaseVersion }}"
        docker build -t modelservicecontainersregistry.azurecr.io/fcs-model-service:${{ inputs.releaseVersion }} .
        echo "Listing Docker images to verify build"
        docker images
        echo "Pushing Docker image with tag ${{ inputs.releaseVersion }}"
        docker push modelservicecontainersregistry.azurecr.io/fcs-model-service:${{ inputs.releaseVersion }}
        echo "Tagging Docker image as latest"
        docker tag modelservicecontainersregistry.azurecr.io/fcs-model-service:${{ inputs.releaseVersion }} modelservicecontainersregistry.azurecr.io/fcs-model-service:latest
        echo "Pushing Docker image with tag latest"
        docker push modelservicecontainersregistry.azurecr.io/fcs-model-service:latest
