name: Build C++ Project - Windows

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      solutionFileName:
        required: true
        type: string
      upload_url:
        required: true
        type: string

jobs:
  build-and-archive:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    # Additional jobs...

    - name: Generate Debug Text File
      run: |
        echo "This is a debug file for testing purposes" > debug.txt
      
    - name: Zip the text file
      run: Compress-Archive -Path debug.txt -DestinationPath win-x64-binaries.zip

    - name: Archive binaries
      uses: actions/upload-artifact@v2
      with:
        name: win-x64-binaries
        path: win-x64-binaries.zip
