name: Publish NPM Package

on:
  workflow_call:
    inputs:
      releaseVersion:
        required: true
        type: string
      upload_url:
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install pre-requisites
        run: npm install

      - name: Build viewer bundle and extract declaration files
        run: npm run build

      - name: Zip viewer bundle assets
        run: |
          zip -r fcs-core-viewer.zip ./fcs-core-viewer

      - name: Attach bundle to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./fcs-core-viewer.zip
          asset_name: fcs-core-viewer.zip
          asset_content_type: application/zip

      - name: Publish declaration files
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
